export const images = [
  {
    id: 1,
    src: "/5212.avif",
    title: "La super nova, la que una sonrisa siempre roba",
    desc: "",
  },
  {
    id: 2,
    src: "/b65d.JPG.avif",
    title: "Que elegancia la de Francia ",
    desc: " ",
  },
  {
    id: 3,
    src: "/232.png.avif",
    title: " Santiago Bernabeu",
    desc: " Congratulation , al equipo merengue",
  },
  {
    id: 4,
    src: "/301.png.avif",
    title: "Wilmer",
    desc: "wilmer de vacaciones. renovando energias",
  },
  {
    id: 5,
    src: "/857.png.avif",
    title: "Comenzando nuevos retos",
    desc: "",
  },
  {
    id: 6,
    src: "/4321.avif",
    title: "la Rivera Coqueta",
    desc: "Tarde Calurosa en casarapa, pensando en como posar para recibir la calida brisa, que transitaba en ese momento. ",
  },
  {
    id: 8,
    src: "/85212.avif",
    title: "Espiritu de la Navidad",
    desc: "con el solsticio de invierno, para iniciar un ciclo de amor, prosperidad y armonia.",
  },
  {
    id: 9,
    src: "/85212.jpg.avif",
    title: "Ser luz en la vida es una dicha",
    desc: "dar alegria y ser bondadoso, ayuda construir y distrir felicidad  ",
  },
  {
    id: 10,
    src: "/85213.avif",
    title: "Arbolito",
    desc: "El rojo, color magico que representa el amor y el ambiente navideño.",
  },
  {
    id: 11,
    src: "/0d6.avif",
    title: "Temperaturas menores de 10 °C",
    desc: "Esta el calido ambiente familiar",
  },
  {
    id: 12,
    src: "/1cd.avif",
    title: "Es lo que siempre he querido",
    desc: " Un rayo de luz Que entró por mi ventana, mi pedazo de sol, la niña de mis ojos ",
  },
  {
    id: 13,
    src: "/6ac1.avif",
    title: "Pijamada",
    desc: " ",
  },
  {
    id: 14,
    src: "/6cb.avif",
    title: "Hala Madrid",
    desc: "En la pantalla, las imagenes cobran vida, la mejor manera de capturar la esencia de nuestra epoca",
  },
  {
    id: 15,
    src: "/21b5.avif",
    title: "Lectora",
    desc: "Autodicta, Le encantta leer y tomar Cafe espresso macchiato.",
  },
  {
    id: 16,
    src: "/9f3.avif",
    title: "Luna de Miel",
    desc: "Tarde de encuentro con los recien casados, mucha dicha y felicidad en su union ",
  },
  {
    id: 17,
    src: "/82f31.avif",
    title: "Verano",
    desc: "Cuando el calor inclemnente nos conduce a parques y albercas.",
  },
  {
    id: 18,
    src: "/2099.avif",
    title: "Espress",
    desc: "Una rapida toma, en direccion al trabajo",
  },
  {
    id: 19,
    src: "/b7e.avif",
    title: "Vampiresa",
    desc: "al borde del peligro",
  },
  {
    id: 20,
    src: "/e848.avif",
    title: "Halloween",
    desc: "asechada por una criatura ",
  },
  {
    id: 21,
    src: "/5e71.avif",
    title: "Corvertida",
    desc: "",
  },
  {
    id: 22,
    src: "/I5967.avif",
    title: "Espresso",
    desc: "Espresso is a concentrated form of coffee, served in shots. It's made of two ingredients - finely ground, 100% coffee, and hot water.",
  },
  {
    id: 23,
    src: "/I5967.avif",
    title: "y esos rulos que?",
    desc: " sera que esa piel es de porcelana",
  },
  {
    id: 24,
    src: "/7232.avif",
    title: "Playeando",
    desc: "",
  },
  {
    id: 25,
    src: "/cb6d.avif",
    title: "atardecer en la playa",
    desc: "",
  },

];
